#!/bin/bash
#SBATCH --nodes=1
#SBATCH -t 0:10:00
#SBATCH --ntasks-per-node=1
#SBATCH --gres=gpu:1

cd /scratch/gpfs/etienneb/SPECFEM-X 

#nvprof  --profile-child-processes 
./bin/specfem-x input/sphere00.sem



